### PR TITLE
Update package to Dart 2.0 support only

### PR DESCRIPTION
**Pull request by Stargator**
I updated the pubspec.yaml to restrict the lower bound SDK constraint to Dart 2.0 and have updated the package version accordingly

Using the Dart Analyzer I addressed what I saw as a few Dart 2.0 related issues. For example, the `new` keyword is no longer required for constructors.

@pulyaevskiy I have the changes in separate commits if there's one you'd prefer I drop.

### CODE REVIEW

**Comment by Stargator** [comment]
Something odd is happening, the tests are failing with Dart 2.2.0, but I run the same command locally and the tests pass. Don't know why the difference yet.

```bash
pub run test -r expanded
00:00 +0: test/test_coverage_test.dart: findTestFiles finds only test files
00:00 +1: test/test_coverage_test.dart: generateMainScript creates main script
00:00 +2: test/test_coverage_test.dart: TestFileInfo for file
00:00 +3: test/test_coverage_test.dart: TestFileInfo for nested file
00:00 +4: All tests passed!
dart --version
Dart VM version: 2.2.0 (Tue Feb 26 15:04:32 2019 +0100) on "macos_x64"
```

**Comment by pulyaevskiy** [comment]
Sorry for silence here.

This looks like a very decent refactor. I'll take a deeper look this week.

Appreciate you taking time to submit this!

**Comment by Stargator** [comment]
@pulyaevskiy No problem, I'll rebase this so the branch is up to date.

**Comment by Stargator** [comment]
@pulyaevskiy Just rebased the branch and accounted for your recent update.

**Review by pulyaevskiy — APPROVED** [review]
LGTM, really like this update!

**Comment by pulyaevskiy** [comment]
Just an FYI: I ended up releasing this as `0.3.0` as I changed a few more things and improved test coverage of the package itself (the package now runs its own test coverage too, successfully solving chicken-and-egg problem).

**Comment by Stargator** [comment]
@pulyaevskiy I saw that, thanks for the update.

I changed my branch from 0.3.0 to 0.2.5 because I saw you had already updated the branch to 2.3.0 and I didn't think my change required such an update on its own.

**Pull request merged**
